config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :channels, except: %i[edit update destroy] do
    resources :memberships, only: %i[create]
    resources :posts, only: %i[create update]
  end
  resources :posts, only: %i[show edit destroy] do
    resources :posts, only: %i[create update]
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :posts, as: :postable, dependent: :destroy

  # Validations
  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }

  # Callbacks
  after_create :assign_owner

  private

  def assign_owner
    Membership.create!(user:, channel: self)
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :channel

  # Validations
  validates :channel, uniqueness: { scope: :user }
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :postable, polymorphic: true
  has_many :replies, as: :postable, class_name: 'Post', dependent: :destroy
  has_rich_text :content

  # Callback
  before_save :flatten_parent_postable

  # Validations
  validates_presence_of :content

  def channel
    postable.instance_of?(Channel) ? postable : postable.postable
  end

  def edited?
    content.created_at != content.updated_at
  end

  def reply?
    postable.instance_of? Post
  end

  private

  def flatten_parent_postable
    return if postable.instance_of?(Channel) || postable.postable.instance_of?(Channel)

    self.postable = postable.postable
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :owned_channels, class_name: 'Channel', dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :channels, through: :memberships
  has_many :posts, dependent: :destroy

  # Callbacks
  before_save :fill_display_name

  private

  def fill_display_name
    return if display_name

    self.display_name = email.gsub(/@.+/, '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_channels

  def configure_permitted_parameters
    additional_fields = %i[display_name full_name title image_url]

    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: additional_fields)

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: additional_fields)
  end

  private

  def set_channels
    return unless current_user

    @channels = current_user.channels.order(:name) || []
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = params[:name] ? search_channels(params[:name]) : nil
    @channel = Channel.new(name: params[:name], user: current_user)
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      respond_to do |format|
        format.html { redirect_to @channel, notice: 'Channel successfully created' }
        format.turbo_stream
      end
    else
      render :index, status: :unprocessable_entity
    end
  end

  def show
    @channel = Channel.find(params[:id])
    @post = Post.new
    @show_replies = true
  end

  private

  def search_channels(name)
    Channel.where('name ILIKE ?', "%#{name}%")
  end

  def channel_params
    params.require(:channel).permit(:name, :description).merge(user: current_user)
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def create
    channel = Channel.find(params[:channel_id])
    @membership = Membership.new(user: current_user, channel:)
    if @membership.save
      respond_to do |format|
        format.html { redirect_to channel }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append(:channels, channel),
            turbo_stream.replace(:modal, '<turbo-frame id="modal"><turbo-frame>')
          ]
        end
      end
    else
      redirect_to root_path, alert: 'You are already a member of this channel'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: %i[create]

  def show
    @channel = @post.channel
    @replies = @post.replies.includes(:user).with_rich_text_content.order(:created_at)
  end

  def create
    @postable = Channel.find(params[:channel_id]) if params[:channel_id]
    @postable = Post.find(params[:post_id]) if params[:post_id]

    @post = Post.new(post_params.merge(user: current_user, postable: @postable))
    if @post.save
      respond_to do |format|
        format.html { redirect_to @postable }
        format.turbo_stream
      end
    else
      flash.now.alert = flat_error_messages
      @channel = @post.channel
      render 'channels/show', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post.postable
    else
      @channel = @post.channel
      flash.now.alert = flat_error_messages
      render 'channels/show', status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    flash.now.notice = 'Post destroyed'
    redirect_to @post.postable
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def flat_error_messages
    @post.errors.messages.map { |k, v| "#{k.capitalize} #{v.join(', ')}" }.join(', ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def user_avatar(user_image:, avatar_size: 'h-7 w-7')
    div_classes = %w[rounded flex overflow-hidden flex-shrink-0].push(avatar_size)
    tag.div class: div_classes do
      if user_image
        tag.image src: user_image
      else
        tag.div class: %w[bg-pink-400 text-white items-center justify-center] do
          tag.i class: %w[fa-solid fa-user]
        end
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def replies_link(post)
    link_to post_path(post), data: { turbo_frame: :right, turbo_action: :advance } do
      tag.div class: wrapper_cls do
        concat(replies_info(post))
        concat(tag.i(class: 'fas fa-chevron-right text-gray-400 text-transparent group-hover/thread:text-gray-400'))
      end
    end
  end

  def replies_info(post)
    tag.div class: 'flex items-center gap-2 text-sm' do
      concat(reply_avatars(post))
      concat(number_of_replies(post.replies.count))
      concat(replies_message(post))
    end
  end

  private

  def reply_avatars(post)
    tag.div class: %w[flex gap-1] do
      User.includes(:posts).where(posts: { postable: post }).distinct.limit(3).pluck(:image_url).map do |image_url|
        concat(user_avatar(user_image: image_url, avatar_size: 'h-5 w-5'))
      end
    end
  end

  def number_of_replies(replies_count)
    tag.span "#{replies_count} #{'reply'.pluralize(replies_count)}", class: 'font-bold text-slack hover:underline'
  end

  def last_reply(post)
    last_created_at = post.replies.order(created_at: :desc).first.created_at
    tag.span "Last reply #{time_ago_in_words(last_created_at)} ago", class: 'group-hover/thread:hidden'
  end

  def view_thread
    tag.span 'View thread', class: 'hidden group-hover/thread:inline'
  end

  def replies_message(post)
    tag.span class: 'text-gray-400' do
      concat(last_reply(post))
      concat(view_thread)
    end
  end

  def wrapper_cls
    %w[flex border rounded border-transparent hover:border-gray-300 hover:bg-white -mx-1 p-1 items-center ] +
      %w[group/thread justify-between]
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/channels/_channel.html.erb
<div class="flex items-center justify-between py-1">
  <%= link_to channel, class: "hover:font-bold #{'font-bold' if current_page?(channel)}" do %>
    <div class="flex gap-2">
      <i class="w-4 mt-[2.5%] text-center <%= channel.private ? 'fa-solid fa-lock' : 'fa-solid fa-hashtag' %>"></i>
      <span class="grow"><%= channel.name %></span>
    </div>
  <% end %>
  <% unless current_user.channels.include?(channel) %>
    <%= form_with url: channel_memberships_path(channel) do |f| %>
      <%= f.button do %>
        <i class="fas fa-user-plus"></i>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/channels/_form.html.erb
<%= form_with url: channels_path,
              method: :get do |f| %>
  <%= f.text_field :name,
                    class: 'w-full rounded border-gray-300 focus:border-slack-extra-light/50 focus:ring-slack-extra-light/50',
                    options: { autofocus: true } %>
  <%= f.submit "Search", class: 'mt-4 w-full bg-slack-medium text-white rounded p-2 cursor-pointer' %>
<% end %>

app/views/channels/create.turbo_stream.erb
<%= turbo_stream.append(:channels, @channel) %>
<%= turbo_stream.replace(:modal, turbo_frame_tag(:modal)) %>

app/views/channels/index.html.erb
<%= render 'shared/modal', modal_title: "Channels" do %>
  <div class="max-h-full flex flex-col overflow-hidden gap-4">
    <%= render 'form' %>
    <div class="max-h-full overflow-y-auto">
      <% if @channels&.none? %>
        <p>No channels with name <em><%= params[:name] %></em> found.</p>
      <% else %>
        <% @channels&.each do |channel| %>
          <%= render channel %>
        <% end %>
      <% end %>
      <% if @channel.valid? %>
        <%= form_with model: @channel do |f| %>
          <%= f.hidden_field :name, value: @channel.name %>
          <%= f.submit "Create ##{@channel&.name}", class: 'font-bold text-slack cursor-pointer' %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/channels/new.html.erb
<%= render 'shared/modal', modal_title: "Search channel" do %>
  <div class="max-h-full flex flex-col overflow-hidden gap-4">
    <%= render 'form' %>
    <div class="max-h-full overflow-y-auto">
    </div>
  </div>
<% end %>

app/views/channels/show.html.erb
<%= turbo_stream_from @channel %>
<div class="h-full flex flex-col">
  <%= render 'pages/top' %>
  <div class="flex grow overflow-hidden">
    <%= render 'pages/left' %>
    <div class="h-full grow flex flex-col shadow-line-left shadow-gray-200 max-w-full overflow-auto">
      <div class="flex gap-2 font-bold px-4 shadow-line-left shadow-gray-200 w-full h-12 shrink-0 items-center justify-center">
        <span class="grow"><%= render @channel %></span>
      </div>
      <div class="grow shrink shadow-line-left shadow-gray-200 w-full overflow-y-auto">
        <div id='posts'>
          <% @channel.posts.includes(:user, :replies).with_rich_text_content.order(:created_at).each do |post| %>
            <%= render post %>
          <% end %>
        </div>
      </div>
      <div id='new-post' class="m-4 border-2 rounded-xl shrink-0 overflow-hidden">
        <%= render 'posts/form', postable: @channel, post: @post %>
      </div>
    </div>
    <%= turbo_frame_tag :right, class: 'max-w-[25vw]' %>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboSlackClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <meta name="view-transition" content="same-origin">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen w-screen fixed">
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= turbo_frame_tag :modal %>
  </body>
</html>

app/views/pages/_center.html.erb
<%= turbo_frame_tag 'center', class: "h-full grow flex flex-col shadow-line-left shadow-gray-200" do %>
  <div class="flex gap-2 font-bold px-4 shadow-line-left shadow-gray-200 w-full h-12 shrink-0 items-center justify-center">
    <%= render 'components/atoms/user_avatar', avatar_size: 'h-6 w-6' %>
    <span class="grow">Username</span>
  </div>
  <div class="grow shrink shadow-line-left shadow-gray-200 w-full overflow-y-auto">
    <% 20.times do |i| %>
    <%# TODO move to a partial 'message' when the model is implemented %>
      <div class="flex w-full px-4 py-2 hover:bg-gray-100">
        <%= render 'components/atoms/user_avatar', avatar_size: 'h-10 w-10' %>
        <%= render 'components/molecules/message_text', username: 'Username', timestamp: Time.now, content: "Message #{i}" %>
      </div>
    <% end %>
  </div>
  <div class="p-4 m-4 border-2 rounded-xl h-32 shrink-0">
  </div>
<% end %>

app/views/pages/_far_left.html.erb
<div class="bg-slack text-white text-sm p-3 shadow-line-left shadow-slack-extra-light flex flex-col gap-4 overflow-y-auto">
  <% 2.times do %>
    <div class="h-7 w-7 rounded flex items-center justify-center shrink-0 bg-emerald-500">
      S
    </div>
  <% end %>
  <%#= link_to new_channel_path, class: 'rounded h-7 w-7 flex items-center justify-center bg-transparent hover:bg-slack-medium', data: { turbo_frame: 'modal' } do %>
    <i class="fa-solid fa-plus"></i>
  <%# end %>
</div>

app/views/pages/_left.html.erb
<div id="left" class='w-52 bg-slack text-white text-sm shadow-line-left shadow-slack-extra-light flex flex-col overflow-y-auto h-full flex-shrink-0'>
  <div class="font-bold px-4 shadow-line-left shadow-slack-extra-light w-full h-12 flex items-center justify-between gap-4 shrink-0">
    <%= link_to root_path do %>
      <div class="w-full text-ellipsis overflow-hidden whitespace-nowrap">Turbo Slack Clone</div>
    <% end %>
    <%= link_to new_channel_path,
                class: "rounded-full bg-white p-2 text-slack flex items-center justify-center text-sm hover:bg-white/25 hover:text-white transition-colors",
                data: { turbo_frame: :modal } do %>
      <i class="fa-regular fa-pen-to-square"></i>
    <% end %>
  </div>
  <div class="text-sm px-4 py-2 shadow-line-left shadow-slack-extra-light w-full text-white/70">
    <% {'Threads' => 'fa-regular fa-comment-dots', 'Direct messages' => 'fa-regular fa-comment-dots', 'Drafts & sent' => 'fa-regular fa-paper-plane', 'Saved items' => 'fa-regular fa-bookmark', 'More' => 'fa-solid fa-ellipsis-vertical'}.each do |text, icon| %>
      <div class="flex items-center py-1">
        <i class="<%= "mr-2 w-4 text-center #{icon}" %>"></i>
        <span class="grow"><%= text %></span>
      </div>
    <% end %>
  </div>
  <div id='channels' class='text-sm px-4 py-2 shadow-line-left shadow-slack-extra-light w-full text-white/70'>
    <% @channels.each do |channel| %>
      <%= render channel %>
    <% end %>
  </div>
</div>

app/views/pages/_top.html.erb
<div id="top" class="bg-slack-dark shadow-line-left shadow-slack-extra-light w-full p-2.5 flex text-white">
  <div class="grow"></div>
  <div class="grow-2 max-w-3xl mx-3 bg-white/20 rounded shadow-sm shadow-black">
    <%= form_with url: '/', method: :get do |f| %>
      <%= f.text_field :query, class: 'border-0 focus:ring-0 bg-transparent w-full text-sm py-1' %>
    <% end %>
  </div>
  <div class="grow flex justify-end">
    <%= link_to destroy_user_session_path, data: { turbo_method: :delete} do %>
      <%= user_avatar user_image: current_user.image_url %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="h-full flex flex-col">
  <%= render 'top' %>
  <div class="flex grow overflow-hidden">
    <%= render 'left' %>
    <div class="h-full grow flex flex-col shadow-line-left shadow-gray-200 max-w-full overflow-auto">
      <div id='content' class="h-full grow flex flex-col max-h-full overflow-hidden">
        <div class="w-full h-full flex flex-col items-center justify-center gap-4">
          <h2 class="text-2xl font-bold leading-10">Hello, <%= current_user.display_name %>! 👋</h2>
          <p>Select a channel or join/create a new one!</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: [postable, post], data: { controller: 'trix' } do |form| %>
  <%= form.rich_text_area :content,
                          placeholder: 'Start a new message',
                          id: dom_id(postable, :form),
                          data: {
                            action: 'keydown->trix#submitWithReturn',
                            trix_target: 'trixEditor'
                          } %>
  <div class="flex justify-end">
    <% if post.new_record? %>
      <%= form.button data: { trix_target: 'button' } do %>
        <i class="fas fa-paper-plane opacity-50 p-2"></i>
      <% end %>
    <% else %>
      <div class="flex gap-2 p-2">
        <%= link_to 'Cancel', postable, class: 'border rounded border-gray-500 text-gray-500 px-4 py-2 hover:bg-gray-100/50' %>
        <%= form.button 'Save', data: { trix_target: 'button' }, class: 'border rounded border-transparent text-white bg-slack px-4 py-2 hover:bg-slack-dark' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id=<%= dom_id post %> class="flex w-full px-4 py-2 hover:bg-gray-100 relative group" data-controller="autoscroll">
  <%= user_avatar(user_image: post.user.image_url, avatar_size: 'h-10 w-10') %>
  <turbo-frame id=<%= dom_id(post, :content)%> class="pl-2 grow max-w-full overflow-hidden">
    <span class="mr-2 font-bold"><%= post.user.display_name %></span>
    <span class="text-xs text-gray-400"><%= post.created_at.strftime("%l:%M%p") %></span>
    <div class="text-sm">
      <%= post.content %>
      <span class="text-xs text-gray-400"><%= '(edited)' if post.edited? %></span>
    </div>
    <div class="hidden group-hover:block absolute right-2 top-2 bg-white rounded border px-2">
      <div class="flex">
        <%= link_to edit_post_path(post),
                    class: 'opacity-50 hover:opacity-100 hover:text-slack p-2' do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to post_path(post),
                    class: 'opacity-50 hover:opacity-100 hover:text-slack p-2',
                    data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this post?' } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
        <% if post.postable.instance_of?(Channel) %>
          <%= link_to post_path(post),
                      class: 'opacity-50 hover:opacity-100 hover:text-slack p-2',
                      data: { turbo_frame: :right, turbo_action: :advance } do %>
          <i class="far fa-comment-dots"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= replies_link post  if @show_replies && post.replies.any? %>
  </turbo-frame>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.update(@post.reply? ? 'new-reply' : 'new-post', partial: 'form', locals: { postable: @post.postable, post: Post.new }) %>
<% @post.broadcast_append_to @post.postable, target: @post.reply? ? :replies : :posts %>

app/views/posts/edit.html.erb
<div class="container m-auto">
  <h1 class="mb-4">Edit post</h1>
  <%= turbo_frame_tag dom_id(@post, :content) do %>
    <div class="border-2 rounded-xl shrink-0 overflow-hidden bg-white">
      <%= render 'form', postable: @post.postable, post: @post %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>
<div class="h-full flex flex-col">
  <%= render 'pages/top' %>
  <div class="flex grow overflow-hidden">
    <%= render 'pages/left' %>
    <%= turbo_frame_tag :right do %>
      <div class="w-full h-full shadow-line-left shadow-gray-200 overflow-y-auto flex flex-col">
        <div class="flex gap-2 font-bold px-4 shadow-line-left shadow-gray-200 w-full h-12 shrink-0 items-center justify-between">
          <span>Thread</span>
          <%= link_to channel_path(@post.channel), data: { turbo_action: :advance} do %>
            <i class="fas fa-times p-3"></i>
          <% end %>
        </div>
        <div class="grow shrink w-full overflow-y-auto">
          <%= render @post %>
          <div>
            <% if @replies.any? %>
              <div class="flex gap-2 px-4 w-full">
                <span class="shrink-0 text-sm text-gray-400">
                  <%= @replies.count %> <%= 'reply'.pluralize(@post.replies.count) %>
                </span>
                <span class="border-t w-full m-auto grow-1"></span>
              </div>
              <div id="replies">
                <% @replies.each do |reply| %>
                  <%= render reply %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div id='new-reply' class="m-4 border-2 rounded-xl shrink-0 overflow-hidden">
          <%= render 'posts/form', postable: @post, post: Post.new %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<%= tag.div id: :flashes do %>
  <% if notice %>
    <div data-controller="flashes" data-flashes-type-value="success" data-flashes-message-value="<%= notice %>"></div>
  <% end %>
  <% if alert %>
    <div data-controller="flashes" data-flashes-type-value="error" data-flashes-message-value="<%= alert %>"></div>
  <% end %>
<% end %>

app/views/shared/_modal.html.erb
<turbo-frame id="modal">
  <div class="absolute z-20 inset-0 flex items-center-justify-center">
    <%= link_to root_path do %>
      <div class="absolute h-full w-full bg-black/70 cursor-default"></div>
    <% end %>
    <div class="z-10 m-auto bg-white rounded h-screen md:h-fit max-h-screen md:max-h-[50vh] w-full md:w-1/2 lg:w-5/12 p-4 overflow-y-auto flex flex-col gap-4">
      <div class="flex w-full gap-4 items-center">
        <h3 class="grow font-bold"><%= modal_title ||= "" %></h3>
        <%= link_to root_path do %>
          <span class="w-8 h-8 flex items-center justify-center rounded hover:bg-gray-100 hover:cursor-pointer">
            <i class="fa-solid fa-xmark grow-0"></i>
          </span>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </div>
</turbo-frame>